name: Build Qt 6.9.0 (LLVM-MinGW20.1.2 x64)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0

jobs:
  build-llvm-mingw:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM-MinGW
        run: |
          choco install -y llvm-mingw --version=20.1.2
          echo "##[add-path]C:\tools\llvm-mingw\bin"
          set CC=clang
          set CXX=clang++
        shell: bash

      - name: Download Qt source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz
        shell: bash

      - name: Build all modes
        run: |
          cd qt-everywhere-src-6.9.0
          for mode in Debug Release DebugAndRelease; do
            mkdir build_$mode && cd build_$mode
            ../configure -prefix $PWD/install -opensource -confirm-license -nomake tests -nomake examples -skip qtwebengine -shared \
              $([ "$mode" == "Debug" ] && echo -debug || ([ "$mode" == "Release" ] && echo -release || echo -debug-and-release))
            cmake --build . --parallel
            cmake --install .
            cd ..
          done
        shell: bash

      - name: Package and Release
        run: |
          for mode in Debug Release DebugAndRelease; do
            cd qt-everywhere-src-6.9.0/build_$mode
            zip -r Qt6.9-llvm-mingw20.1.2-x64-$mode-shared.zip install
            gh release create v6.9.0-$mode-llvm-mingw Qt6.9-llvm-mingw20.1.2-x64-$mode-shared.zip --title "Qt 6.9.0 $mode (LLVM-MinGW20.1.2 x64)"
            cd ../../
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
