name: Build Qt 6.9.0 (MSVC2022 x64)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0

jobs:
  build-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release, DebugAndRelease]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'
          msbuild-architecture: x64

      - name: Download & extract Qt source (PowerShell)
        shell: pwsh
        run: |
          Invoke-WebRequest https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz -OutFile qt-everywhere-src-6.9.0.tar.xz
          tar -xf qt-everywhere-src-6.9.0.tar.xz



      - name: Configure Qt
        shell: cmd
        run: |
          cd qt-everywhere-src-6.9.0
          mkdir build && cd build
          set BUILD_FLAGS=-prefix %CD%/install -opensource -confirm-license -nomake tests -nomake examples -skip qtwebengine -shared
          if "%BUILD_TYPE%"=="Debug" set BUILD_FLAGS=%BUILD_FLAGS% -debug
          if "%BUILD_TYPE%"=="Release" set BUILD_FLAGS=%BUILD_FLAGS% -release
          if "%BUILD_TYPE%"=="DebugAndRelease" set BUILD_FLAGS=%BUILD_FLAGS% -debug-and-release
          cmd /c "configure.bat %BUILD_FLAGS%"

      - name: Build
        shell: cmd
        run: |
          cd qt-everywhere-src-6.9.0\build
          cmake --build . --config %BUILD_TYPE% --parallel

      - name: Install
        shell: cmd
        run: |
          cd qt-everywhere-src-6.9.0\build
          cmake --install . --config %BUILD_TYPE%

      - name: Package
        shell: cmd
        run: |
          cd qt-everywhere-src-6.9.0\build
          set ARCHIVE=Qt6.9-msvc2022-x64-%BUILD_TYPE%-shared.zip
          powershell Compress-Archive -Path install -DestinationPath %ARCHIVE%
          echo "ARCHIVE=%ARCHIVE%" >> %GITHUB_ENV%

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v6.9.0-%BUILD_TYPE%-msvc2022
          release_name: Qt 6.9.0 %BUILD_TYPE% (MSVC2022 x64)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE }}
