name: Build Qt 6.9.0 Dynamic (MSVC2022 + Ninja, Multi Config)

on:
  workflow_dispatch:

jobs:
  build-qt-windows:
    runs-on: windows-latest
    name: Build Qt (Windows MSVC2022 Dynamic All Modes)
    env:
      QT_VERSION: 6.9.0
      QT_FOLDER: D:\a\buildQt\Qt
      MSVC_VERSION: msvc2022_64_RP

    steps:
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Download Qt source (qtbase/qttools/qttranslations/qtsvg)
        run: |
          $baseUrl = "https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules"
          $qtVersion = "${{ env.QT_VERSION }}"
          $qtPath = "${{ env.QT_FOLDER }}\$qtVersion"

          $modules = @(
            "qtbase-everywhere-src-$qtVersion",
            "qttools-everywhere-src-$qtVersion",
            "qttranslations-everywhere-src-$qtVersion",
            "qtsvg-everywhere-src-$qtVersion"
          )

          foreach ($mod in $modules) {
            $zipName = "$mod.zip"
            $url = "$baseUrl/$zipName"
            Invoke-WebRequest -Uri $url -OutFile $zipName
            Expand-Archive -Path $zipName -DestinationPath "$qtPath"
          }

      - name: Set up MSVC2022 environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build all configurations
        shell: cmd
        run: |
          set QT_VERSION=${{ env.QT_VERSION }}
          set QT_DIR=${{ env.QT_FOLDER }}\%QT_VERSION%
          set MSVC_VERSION=${{ env.MSVC_VERSION }}

          set SRC_BASE=%QT_DIR%\qtbase-everywhere-src-%QT_VERSION%
          set SRC_TOOLS=%QT_DIR%\qttools-everywhere-src-%QT_VERSION%
          set SRC_TRANS=%QT_DIR%\qttranslations-everywhere-src-%QT_VERSION%
          set SRC_SVG=%QT_DIR%\qtsvg-everywhere-src-%QT_VERSION%

          for %%C in (Debug Release RelWithDebInfo) do (
            echo ==== Building Qt %%C ====

            set INSTALL_DIR=${{ env.QT_FOLDER }}\%QT_VERSION%-dynamic\%MSVC_VERSION%-%%C
            set BUILD_DIR_BASE=%QT_DIR%\build-qtbase-%%C

            if exist "%%BUILD_DIR_BASE%%" rmdir /s /q "%%BUILD_DIR_BASE%%"
            mkdir "%%BUILD_DIR_BASE%%" && cd /d "%%BUILD_DIR_BASE%%"

            call %SRC_BASE%\configure.bat -%%C -nomake examples -prefix %%INSTALL_DIR%% -opensource -confirm-license -qt-libpng -qt-libjpeg -qt-zlib -qt-pcre -qt-freetype -schannel -opengl desktop -platform win32-msvc
            cmake --build . --parallel
            cmake --install .

            for %%M in (qttools qttranslations qtsvg) do (
              echo === Building %%M for %%C ===
              set SRC_DIR=%QT_DIR%\%%M*-src-%QT_VERSION%
              set BUILD_DIR=%QT_DIR%\build-%%M-%%C

              if exist "%%BUILD_DIR%%" rmdir /s /q "%%BUILD_DIR%%"
              mkdir "%%BUILD_DIR%%" && cd /d "%%BUILD_DIR%%"

              cmake "%%SRC_DIR%%" -G "Ninja" -DCMAKE_INSTALL_PREFIX=%%INSTALL_DIR%% -DCMAKE_BUILD_TYPE=%%C -DCMAKE_PREFIX_PATH=%%INSTALL_DIR%%\lib\cmake
              cmake --build . --parallel
              cmake --install .
            )

            echo [Paths]> %%INSTALL_DIR%%\bin\qt.conf
            echo Prefix=..>> %%INSTALL_DIR%%\bin\qt.conf

            echo === Compressing %%C ===
            "C:\Program Files\7-Zip\7z.exe" a -t7z qt-%QT_VERSION%-%MSVC_VERSION%-%%C.7z %%INSTALL_DIR%%\*
          )

      - name: Upload Debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-Debug
          path: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-Debug.7z

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-Release
          path: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-Release.7z

      - name: Upload RelWithDebInfo artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-RelWithDebInfo
          path: qt-${{ env.QT_VERSION }}-${{ env.MSVC_VERSION }}-RelWithDebInfo.7z
