name: Build Qt 6.9.0 (MinGW1420 x64)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0

jobs:
  build-mingw:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MinGW UCRT
        run: |
          choco install -y mingw --version=14.2.0
          echo "##[add-path]C:\tools\mingw64\ucrt64\bin"
          set CC=x86_64-w64-mingw32-gcc
          set CXX=x86_64-w64-mingw32-g++.exe
        shell: bash

      - name: Download Qt source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz
        shell: bash

      - name: Build all modes
        run: |
          cd qt-everywhere-src-6.9.0
          for mode in Debug Release DebugAndRelease; do
            mkdir build_$mode && cd build_$mode
            ../configure -prefix $PWD/install -opensource -confirm-license -nomake tests -nomake examples -skip qtwebengine -shared \
              $([ "$mode" == "Debug" ] && echo -debug || ([ "$mode" == "Release" ] && echo -release || echo -debug-and-release))
            cmake --build . --parallel
            cmake --install .
            cd ..
          done
        shell: bash

      - name: Package and Release
        run: |
          for mode in Debug Release DebugAndRelease; do
            cd qt-everywhere-src-6.9.0/build_$mode
            zip -r Qt6.9-mingw1420-x64-$mode-shared.zip install
            gh release create v6.9.0-$mode-mingw1420 Qt6.9-mingw1420-x64-$mode-shared.zip --title "Qt 6.9.0 $mode (MinGW1420 x64)"
            cd ../../
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
