name: Build MinGW-w64 from source

on:
  workflow_dispatch:

jobs:
  build-mingw64:
    name: Build MinGW-w64 – ${{ matrix.thread }} with ${{ matrix.crt }} for Windows (x86_64)
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    - name: ls path
      shell: msys2 {0}
      run: |
        ls