name: check msys2 env

on: 
  workflow_dispatch:

jobs:
  check-msys-env:
    name: check-msys-env
    runs-on: windows-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set Msys2 Env
        uses: msys2/setup-msys2@v2
        with: 
          update: true

      - name: PWD
        shell: msys2 {0}
        run: |
          pwd
      - name: ls
        shell: msys2 {0}
        run: |
          ls
      - name: find gcc
        shell: msys2 {0}
        run: |
          ls /usr/bin/
        
