name: Build QT add QtWebEngine

on:
  workflow_dispatch:
    inputs:
      qt_majmin:
        description: 'Qt 主版本号与次版本号(>=6.7.0)'
        required: true
        default: '6.8'
      qt_patch:
        description: 'Qt 补丁版本号(例如 0)'
        required: false
        default: '3'

jobs:
  build-add-qtwebengine:
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        config: [Debug, Release, RelWithDebInfo]
    env:
      QT_MAJMIN: ${{ inputs.qt_majmin }}
      QT_VERSION: ${{ inputs.qt_majmin }}.${{ inputs.qt_patch }}
      TAG: v${{ inputs.qt_majmin }}.${{ inputs.qt_patch }}-shared
      GITHUB_REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
      QT_SOURCE_URL: https://download.qt.io/archive/qt/${{ inputs.qt_majmin }}/${{ inputs.qt_majmin }}.${{ inputs.qt_patch }}/single/qt-everywhere-src-${{ inputs.qt_majmin }}.${{ inputs.qt_patch }}.zip

    steps:
      - uses: actions/checkout@v4

      - name: download artifact from other action
        env:
          CONFIG: ${{ matrix.config }}
          QT_DEBUG_URL: https://productionresultssa2.blob.core.windows.net/actions-results/8d7cb665-c19f-46ec-a385-579713952d9f/workflow-job-run-eeeaef35-d6e2-57c5-9add-c508ea42f755/artifacts/de6aa47d092fe7bfce0c91ee432bdb49a6ad8a324fef0ecad92656b559ad9836.zip?rscd=attachment%3B+filename%3D%22qt-6.8.3-shared-win-msvc2022-Debug.zip%22&se=2025-10-20T10%3A55%3A53Z&sig=gOqJAJCTBdm4YmapEm02Miiw8akygECORoS%2FWq555ys%3D&ske=2025-10-20T21%3A33%3A51Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-10-20T09%3A33%3A51Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2025-10-20T10%3A45%3A48Z&sv=2025-11-05
          QT_RELEASE_URL: https://productionresultssa2.blob.core.windows.net/actions-results/8d7cb665-c19f-46ec-a385-579713952d9f/workflow-job-run-4ecee265-39de-5b6f-9527-5eb3874b4558/artifacts/d7c8222f4897ea2aa8197127b634372f134d0a11760cf9c892e06b5ca20007d6.zip?rscd=attachment%3B+filename%3D%22qt-6.8.3-shared-win-msvc2022-Release.zip%22&se=2025-10-20T10%3A57%3A40Z&sig=WFn8pgIgdQ9WSUkSDm7UNijmWUKumOcFJ10%2Bj%2Bqley0%3D&ske=2025-10-20T21%3A34%3A13Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-10-20T09%3A34%3A13Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2025-10-20T10%3A47%3A35Z&sv=2025-11-05
          QT_RELWITHDEB_URL: https://productionresultssa2.blob.core.windows.net/actions-results/8d7cb665-c19f-46ec-a385-579713952d9f/workflow-job-run-73e6c851-6d2e-54cb-899c-1db7757153b0/artifacts/9dd60f664afb6b79b5b3dca9f94f3d6172390d01fc54a7db9138af71d4d8475a.zip?rscd=attachment%3B+filename%3D%22qt-6.8.3-shared-win-msvc2022-RelWithDebInfo.zip%22&se=2025-10-20T10%3A57%3A02Z&sig=1t2GojCMKxUIoU6rwavvlXWlvLcMn66o5ZqLJSeI7YQ%3D&ske=2025-10-20T21%3A33%3A40Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-10-20T09%3A33%3A40Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2025-10-20T10%3A46%3A57Z&sv=2025-11-05
        run: |
          $dest = Join-Path $env:RUNNER_TEMP ("qt-" + $env:QT_VERSION)
          New-Item -Path $dest -ItemType Directory -Force | Out-Null
          $zip = Join-Path $env:RUNNER_TEMP/qt-$env:QT_VERSION qt-$env:QT_VERSION-shared-win-msvc2022-${{ matrix.config }}.zip
          $qt_in_zip = Join-Path $env:RUNNER_TEMP/qt-$env:QT_VERSION qt-$env:QT_VERSION-shared-win-msvc2022-${{ matrix.config }}.7z
          $url = switch ($env:CONFIG) {
            'Debug' { $env:QT_DEBUG_URL }
            'Release' { $env:QT_RELEASE_URL }
            'RelWithDebInfo' { $env:QT_RELWITHDEB_URL }
            default { throw "Unknown CONFIG: $env:CONFIG" }
          }
          Invoke-WebRequest $url -OutFile $zip
          7z x $zip -y -o"$dest" -mmt=on
          Remove-Item $zip
          7z x $qt_in_zip -y -o"$dest" -mmt=on
          Remove-Item $qt_in_zip

      - name: new cmake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '3.29.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      - run: pip install html5lib

      - name: Cache Qt source
        id: cache-qt-source
        uses: actions/cache@v3
        with:
          key: qt-src-${{ env.QT_VERSION }}-windows
          path: ${{ runner.temp }}/qt6_src/qt-everywhere-src-${{ env.QT_VERSION }}

      - name: Cache llvm for ${{ matrix.config }}
        id: cache-llvm
        uses: actions/cache@v3
        with:
          key: llvm-${{ matrix.config }}-windows
          path: ${{ runner.temp }}/llvm-${{ matrix.config }}

      - name: Download llvm for ${{ matrix.config }}
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        shell: pwsh
        env:
          CONFIG: ${{ matrix.config }}
        run: |
          $llvm_url = "https://github.com/RiverBreaker/build-llvm/releases/download/llvm-20.1.0/llvm-20.1.0-win-x86-$env:CONFIG.7z"
          $llvm_zip = Join-Path $env:RUNNER_TEMP llvm-$env:CONFIG.7z
          Invoke-WebRequest $llvm_url -OutFile $llvm_zip
          7z x $llvm_zip -y -o"$env:RUNNER_TEMP/llvm-$env:CONFIG" -mmt=on

      - name: Download & extract Qt
        if: steps.cache-qt-source.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $qt_zip = Join-Path $env:RUNNER_TEMP qt6.zip
          Invoke-WebRequest $env:QT_SOURCE_URL -OutFile $qt_zip
          7z x $qt_zip -y -o"$env:RUNNER_TEMP\qt6_src" -mmt=on

      - name: Install build tools via Chocolatey
        shell: pwsh
        env:
          CONFIG: ${{ matrix.config }}
          QT_VERSION: ${{ env.QT_VERSION }}
        run: |
          choco install -y 7zip gperf winflexbison3 `
            --no-progress `
            --limit-output
          choco install -y openssl --version=3.5.4 --no-progress --limit-output

          Remove-Item -Recurse -Force "$env:RUNNER_TEMP/build" -ErrorAction SilentlyContinue
          New-Item -ItemType Directory "$env:RUNNER_TEMP/build" | Out-Null
          New-Item -ItemType Directory "$env:RUNNER_TEMP/qt-$env:QT_VERSION" | Out-Null

      - name: Apply patch
        shell: bash
        run: |
          cd $RUNNER_TEMP/qt6_src/qt-everywhere-src-$QT_VERSION
          patch -p1 -i "$GITHUB_WORKSPACE/patchs/fixed-qtwebengine-build-on-windows.patch"

      - name: Configure & build & install ${{ matrix.config }}
        shell: cmd
        env:
          CONFIG: ${{ matrix.config }}
        run: |
          rem 1. 查找 VS2022 安装路径并加载编译环境
          setlocal enabledelayedexpansion

          if "${{ inputs.qt_majmin >= '6.5' }}" == "true" (
            echo "Using VS2022"
            set "vsRoot=C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
            echo Using vsRoot=!vsRoot!
            call "!vsRoot!\VC\Auxiliary\Build\vcvarsall.bat" amd64 || (echo vcvarsall failed && exit /b 1)
          ) else (
            echo "Using VS2019"
            call "%GITHUB_WORKSPACE%\scripts\window_s\vs_setup_v142.cmd" || exit /b 1
          )

          where cl >nul 2>&1 || (echo ERROR: cl not found in PATH after vcvars && exit /b 1)

          rem 2. 设置路径
          set "SRC_QT=%RUNNER_TEMP%\qt6_src\qt-everywhere-src-%QT_VERSION%"
          set "QTWEBENGINE_SRC=%SRC_QT%\qtwebengine"
          set "BUILD_DIR=%RUNNER_TEMP%\build-%CONFIG%"
          set "INSTALL_DIR=%RUNNER_TEMP%\qt-%QT_VERSION%\%CONFIG%"
          set "ARTIFACTS_DIR=%RUNNER_TEMP%\artifacts"

          rem 3. 清理/创建
          if exist "%BUILD_DIR%" rmdir /s /q "%BUILD_DIR%"
          mkdir "%BUILD_DIR%" && cd "%BUILD_DIR%"
          mkdir "%INSTALL_DIR%" 2>nul
          mkdir "%ARTIFACTS_DIR%" 2>nul

          rem 4. 选择模式
          if /I "%CONFIG%"=="Debug" (
            set MODE=-debug
          ) else if /I "%CONFIG%"=="Release" (
            set MODE=-release
          ) else (
            set MODE=-debug-and-release
          )

          rem 5. 调用 configure
          call "%INSTALL_DIR%\bin\qt-configure-module.bat" ^
            %QTWEBENGINE_SRC% ^
            -shared %MODE% -prefix "%INSTALL_DIR%" ^
            -nomake examples -nomake tests ^
            -opensource -confirm-license ^
            -platform win32-msvc ^
            -- ^
            -DLLVM_INSTALL_DIR="%RUNNER_TEMP%\llvm-%CONFIG%" ^
            -DFEATURE_clang=ON -DFEATURE_clangcpp=ON ^
            -Wno-dev

          rem check whether wrapper already created CMake cache/buildsystem
          if exist CMakeCache.txt (
            echo "CMakeCache.txt exists (wrapper likely ran cmake). Skipping explicit cmake configure."
          ) else (
            echo "No CMakeCache.txt found — running explicit cmake configure..."
            cmake -S . -B . -Wno-dev || (echo ERROR: cmake configure failed && exit /b 1)
          )

          rem build & install (ensure --config)
          cmake --build . --config %CONFIG% --parallel || (echo ERROR: build failed && exit /b 1)
          cmake --install . --config %CONFIG% --prefix "%INSTALL_DIR%" || (echo ERROR: install failed && exit /b 1)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qt-${{ env.QT_VERSION }}-with-qtwebengine-shared-win-msvc2022-${{ matrix.config }}
          path: ${{ runner.temp }}/qt-${{ env.QT_VERSION }}/${{ matrix.config }}